SYSTEM_API_KEYS = [
    ("Hostname", ["HostName"], ["Summary"]),
    ("PCIe Devices Count", ["PCIeDevices@odata.count"], ["Hardware|Chassis"]),
    ("Part Number", ["PartNumber"], ["Hardware|Chassis"]),
    ("Power State", ["PowerState"], ["Settings|Power"]),
    ("SKU", ["SKU"], ["Summary"]),
    ("Serial Number", ["SerialNumber"], ["Summary"]),
    ("Manufacturer", ["Manufacturer"], ["Summary"]),
    ("Model", ["Model"], ["Summary"]),
    ("Location Indicator Active", ["LocationIndicatorActive"], ["Settings|Other"]),
    ("CPU Count", ["ProcessorSummary", "Count"], ["Hardware|CPU"]),
    ("Core Count", ["ProcessorSummary", "CoreCount"], ["Hardware|CPU"]),
    ("Logical Processor Count", ["ProcessorSummary", "LogicalProcessorCount"], ["Hardware|CPU"]),
    ("Model", ["ProcessorSummary", "Model"], ["Hardware|CPU"]),
    ("Threading Enabled", ["ProcessorSummary", "ThreadingEnabled"], ["Hardware|CPU"]),
    ("CPU Health Status", ["ProcessorSummary", "Status", "Health"], ["Hardware|Status"]),
    ("CPU Health Rollup", ["ProcessorSummary", "Status", "HealthRollup"], ["Hardware|Status"]),
    ("State", ["ProcessorSummary", "Status", "State"], ["Hardware|CPU"]),
    ("Total System Memory GiB", ["MemorySummary", "TotalSystemMemoryGiB"], ["Hardware|Memory"]),
    ("Version", ["BiosVersion"], ["Settings|BIOS"]),
    ("Boot Progress Last State", ["BootProgress", "LastState"], ["Settings|BIOS"]),
    ("Boot Source Override Enabled", ["Boot", "BootSourceOverrideEnabled"], ["Settings|BIOS"]),
    ("Boot Source Override Mode", ["Boot", "BootSourceOverrideMode"], ["Settings|BIOS"]),
    ("Boot Source Override Target", ["Boot", "BootSourceOverrideTarget"], ["Settings|BIOS"]),
    ("UEFI Target Boot Source Override", ["Boot", "UefiTargetBootSourceOverride"], ["Settings|BIOS"]),
    ("Stop Boot On Fault", ["Boot", "StopBootOnFault"], ["Settings|BIOS"]),
    ("BIOS Release Date", ["Oem", "Dell", "DellSystem", "BIOSReleaseDate"], ["Settings|BIOS"]),
    ("Connect Types Supported", ["GraphicalConsole", "ConnectTypesSupported", 0], ["Settings|Console"]),
    ("Max Concurrent Sessions", ["GraphicalConsole", "MaxConcurrentSessions"], ["Settings|Console"]),
    ("Service Enabled", ["GraphicalConsole", "ServiceEnabled"], ["Settings|Console"]),
    ("Last Reset Time", ["LastResetTime"], ["Settings|Console"]),
    ("Fan Count", ["Links", "CooledBy@odata.count"], ["Hardware|Cooler"]),
    ("Base Board Chassis Slot", ["Oem", "Dell", "DellSystem", "BaseBoardChassisSlot"], ["Hardware|Chassis"]),
    ("Battery Rollup Status", ["Oem", "Dell", "DellSystem", "BatteryRollupStatus"], ["Hardware|Status"]),
    ("Blade Geometry", ["Oem", "Dell", "DellSystem", "BladeGeometry"], ["Hardware|Chassis"]),
    ("CMCIP", ["Oem", "Dell", "DellSystem", "CMCIP"], ["Hardware|Chassis"]),
    ("CMC Rollup Status", ["Oem", "Dell", "DellSystem", "CMCRollupStatus"], ["Hardware|Status"]),
    ("CPU Rollup Status", ["Oem", "Dell", "DellSystem", "CPURollupStatus"], ["Hardware|Status"]),
    ("Chassis Model", ["Oem", "Dell", "DellSystem", "ChassisModel"], ["Hardware|Chassis"]),
    ("Chassis Name", ["Oem", "Dell", "DellSystem", "ChassisName"], ["Hardware|Chassis"]),
    ("Chassis Service Tag", ["Oem", "Dell", "DellSystem", "ChassisServiceTag"], ["Hardware|Chassis"]),
    ("Chassis System Height Unit", ["Oem", "Dell", "DellSystem", "ChassisSystemHeightUnit"], ["Hardware|Chassis"]),
    ("Cooling Rollup Status", ["Oem", "Dell", "DellSystem", "CoolingRollupStatus"], ["Hardware|Status"]),
    ("Current Rollup Status", ["Oem", "Dell", "DellSystem", "CurrentRollupStatus"], ["Hardware|Status"]),
    ("Estimated Exhaust Temperature Celsius", ["Oem", "Dell", "DellSystem", "EstimatedExhaustTemperatureCelsius"], ["Hardware|Cooler"]),
    ("Estimated System Airflow CFM", ["Oem", "Dell", "DellSystem", "EstimatedSystemAirflowCFM"], ["Hardware|Cooler"]),
    ("Express Service Code", ["Oem", "Dell", "DellSystem", "ExpressServiceCode"], ["Hardware|Chassis"]),
    ("Fan Rollup Status", ["Oem", "Dell", "DellSystem", "FanRollupStatus"], ["Hardware|Status"]),
    ("IDSDM Redundancy Status", ["Oem", "Dell", "DellSystem", "IDSDMRedundancyStatus"], ["Hardware|Status"]),
    ("IDSDM Rollup Status", ["Oem", "Dell", "DellSystem", "IDSDMRollupStatus"], ["Hardware|Status"]),
    ("Intrusion Rollup Status", ["Oem", "Dell", "DellSystem", "IntrusionRollupStatus"], ["Hardware|Status"]),
    ("Is OEM Branded", ["Oem", "Dell", "DellSystem", "IsOEMBranded"], ["Hardware|Chassis"]),
    ("Last System Inventory Time", ["Oem", "Dell", "DellSystem", "LastSystemInventoryTime"], ["Settings|Other"]),
    ("Last Update Time", ["Oem", "Dell", "DellSystem", "LastUpdateTime"], ["Settings|Other"]),
    ("Licensing Rollup Status", ["Oem", "Dell", "DellSystem", "LicensingRollupStatus"], ["Hardware|Status"]),
    ("Managed System Size", ["Oem", "Dell", "DellSystem", "ManagedSystemSize"], ["Hardware|Chassis"]),
    ("Max CPU Sockets", ["Oem", "Dell", "DellSystem", "MaxCPUSockets"], ["Hardware|Chassis"]),
    ("Max DIMM Slots", ["Oem", "Dell", "DellSystem", "MaxDIMMSlots"], ["Hardware|Chassis"]),
    ("Max PCIe Slots", ["Oem", "Dell", "DellSystem", "MaxPCIeSlots"], ["Hardware|Chassis"]),
    ("Memory Operation Mode", ["Oem", "Dell", "DellSystem", "MemoryOperationMode"], ["Hardware|Chassis"]),
    ("PS Rollup Status", ["Oem", "Dell", "DellSystem", "PSRollupStatus"], ["Hardware|Status"]),
    ("Platform GUID", ["Oem", "Dell", "DellSystem", "PlatformGUID"], ["Hardware|Chassis"]),
    ("Populated DIMM Slots", ["Oem", "Dell", "DellSystem", "PopulatedDIMMSlots"], ["Hardware|Chassis"]),
    ("Populated PCIe Slots", ["Oem", "Dell", "DellSystem", "PopulatedPCIeSlots"], ["Hardware|Chassis"]),
    ("Power Cap Enabled State", ["Oem", "Dell", "DellSystem", "PowerCapEnabledState"], ["Hardware|Chassis"]),
    ("SD Card Rollup Status", ["Oem", "Dell", "DellSystem", "SDCardRollupStatus"], ["Hardware|Status"]),
    ("SEL Rollup Status", ["Oem", "Dell", "DellSystem", "SELRollupStatus"], ["Hardware|Status"]),
    ("Server Allocation Watts", ["Oem", "Dell", "DellSystem", "ServerAllocationWatts"], ["Settings|Power"]),
    ("Storage Rollup Status", ["Oem", "Dell", "DellSystem", "StorageRollupStatus"], ["Hardware|Status"]),
    ("SysMem Error Methodology", ["Oem", "Dell", "DellSystem", "SysMemErrorMethodology"], ["Hardware|Chassis"]),
    ("SysMem FailOver State", ["Oem", "Dell", "DellSystem", "SysMemFailOverState"], ["Hardware|Chassis"]),
    ("SysMem Location", ["Oem", "Dell", "DellSystem", "SysMemLocation"], ["Hardware|Chassis"]),
    ("SysMem Primary Status", ["Oem", "Dell", "DellSystem", "SysMemPrimaryStatus"], ["Hardware|Status"]),
    ("System Generation", ["Oem", "Dell", "DellSystem", "SystemGeneration"], ["Hardware|Chassis"]),
    ("System Health Rollup Status", ["Oem", "Dell", "DellSystem", "SystemHealthRollupStatus"], ["Hardware|Status"]),
    ("System ID", ["Oem", "Dell", "DellSystem", "SystemID"], ["Hardware|Chassis"]),
    ("System Revision", ["Oem", "Dell", "DellSystem", "SystemRevision"], ["Hardware|Chassis"]),
    ("Temp Rollup Status", ["Oem", "Dell", "DellSystem", "TempRollupStatus"], ["Hardware|Status"]),
    ("Temp Statistics Rollup Status", ["Oem", "Dell", "DellSystem", "TempStatisticsRollupStatus"], ["Hardware|Status"]),
    ("Chassis UUID", ["Oem", "Dell", "DellSystem", "UUID"], ["Summary"]),
    ("Volt Rollup Status", ["Oem", "Dell", "DellSystem", "VoltRollupStatus"], ["Hardware|Status"]),
    ("Chassis SMBIOS GUID", ["Oem", "Dell", "DellSystem", "smbiosGUID"], ["Summary"]),
    ("TPM Firmware Version", ["TrustedModules", 0, "FirmwareVersion"], ["Security|TPM"]),
    ("TPM InterfaceType", ["TrustedModules", 0, "InterfaceType"], ["Security|TPM"]),
    ("TPM Status", ["TrustedModules", 0, "Status", "State"], ["Hardware|Status"]),
    ("TPM Count", ["TrustedModules@odata.count"], ["Security|TPM"]),
]